# fly.toml file generated for an-caotharnach on 2023-08-07T12:35:38+02:00

app = "an-caotharnach"
kill_signal = "SIGINT"
kill_timeout = 5
mounts = []
processes = []

[build]
  builder = "heroku/builder:24"

[env]
  PORT = "8080"

[deploy]
  release_command = "bundle exec rackup -p 8080"

[[services]]
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443
